//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class contato
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Contato { get; set; }
        public int IdCliente { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
